#!/bin/sh

hex2bin() {

	echo $1 | tr '[a-z]' '[A-Z]' | sed 's/://g' | sed 's/.\B/&\n/g' | {
		buf=""
		while read char
		do
			case "$char" in 
			0) buf="${buf}0000" ;;
			1) buf="${buf}0001" ;;
			2) buf="${buf}0010" ;;
			3) buf="${buf}0011" ;;
			4) buf="${buf}0100" ;;
			5) buf="${buf}0101" ;;
			6) buf="${buf}0110" ;;
			7) buf="${buf}0111" ;;
			8) buf="${buf}1000" ;;
			9) buf="${buf}1001" ;;
			A) buf="${buf}1010" ;;
			B) buf="${buf}1011" ;;
			C) buf="${buf}1100" ;;
			D) buf="${buf}1101" ;;
			E) buf="${buf}1110" ;;
			F) buf="${buf}1111" ;;
			esac
		done

		echo $buf
	
	}
}

bin2hex() {

	echo $1 | sed 's/....\B/&\n/g' | {
		buf=""
		while read char
		do
			case "$char" in
				0000) buf="${buf}0" ;;
				0001) buf="${buf}1" ;;
				0010) buf="${buf}2" ;;
				0011) buf="${buf}3" ;;
				0100) buf="${buf}4" ;;
				0101) buf="${buf}5" ;;
				0110) buf="${buf}6" ;;
				0111) buf="${buf}7" ;;
				1000) buf="${buf}8" ;;
				1001) buf="${buf}9" ;;
				1010) buf="${buf}A" ;;
				1011) buf="${buf}B" ;;
				1100) buf="${buf}C" ;;
				1101) buf="${buf}D" ;;
				1110) buf="${buf}E" ;;
				1111) buf="${buf}F" ;;
			esac
		done

		echo $buf
	}
}

expandip () {

	ipv6address=$(echo $1 | sed -e :a -e 's/\b[0-9A-F]\{1,3\}\b/0&/gI;ta')
	postsegments=$(echo $ipv6address | awk -F'::' '{print $2}'  | awk -F ':' '{print NF}')

	expandedipv6=$(echo $ipv6address | awk -F'::' '{print $1}' | sed 's/://g')
	expandedipv6=$(echo $expandedipv6 | sed -e :a -e 's/^[0-9A-F]\{1,'$(((8 - $postsegments) * 4 - 1))'\}$/&0/gI;ta')
	expandedipv6=$expandedipv6$(echo $ipv6address | awk -F'::' '{print $2}' | sed 's/://g')

	echo $expandedipv6 | sed 's/....\B/&:/g'
}

makeprefix () {

	if [ $(($2 % 4)) -ne 0 ] ; then
		prefix=$(echo $1 | cut -c 1-$(($2 / 4 + 1)))
	else
		prefix=$(echo $1 | cut -c 1-$(($2 / 4)))
	fi

	if [ $(($2 % 16)) -ne 0 ] ; then
		prefix=$(echo $prefix | sed -e :a -e 's/^[0-9A-F]\{1,'$((($2 / 16 + 1) * 16 / 4 - 1))'\}$/&0/gI;ta')
	fi

	echo $prefix | sed 's/....\B/&:/g' | sed 's/\:0\{1,3\}/:/g'
}

# Set Path
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Get Time Zone
if [ -z $TZ ]; then
	if [ -s /tmp/TZ ]; then
		TZ=$(cat /tmp/TZ)
	elif [ -s /etc/timezone ]; then
		TZ=$(cat /etc/timezone)
	fi
fi
