#!/bin/sh

echo "######################################"
echo "Activating router"
echo "######################################"
echo
echo "The activate script will replace the temporary network and dhcp settings with"
echo "your configured settings"
echo
echo "After running the activate script, the router WILL SHUT DOWN"
echo
echo "The router will be fully active the next time you boot."
echo "Make sure the original router is shutdown before booting."
echo

while true; do
	read -p "Continue (y/n)? " yn
	case $yn in
		[Yy]* )
			break;;
		[Nn]* )
			echo "Exiing ..."
			exit
			break;;
	esac
done

echo
echo "######################################"
echo "Replacing temporary install files"
echo "######################################"
echo
	
if [ -s /opt/router/install/.activated ]; then
	echo "Router already activated ... skipping"
else
	echo "copying /etc/network/interfaces.router -> /etc/network/interfaces"
	cp /etc/network/interfaces.router /etc/network/interfaces

	echo "copying /opt/router/dnsmasq/dnsmasq.conf.router -> /opt/router/dnsmasq/dnsmasq.conf"
	cp /opt/router/dnsmasq/dnsmasq.conf.router /opt/router/dnsmasq/dnsmasq.conf
	
	echo $(date +%s) > /opt/router/install/.activated
fi

echo
echo "######################################"
echo "Remapping config symlinks"
echo "######################################"
echo

echo -n "remapping ~/router/config/network_interfaces -> /etc/network/interfaces"
ln -sf /etc/network/interfaces /root/router/config/network_interfaces && echo ok || echo FAILED

echo -n "remapping ~/router/config/dhcp_base -> /opt/router/dnsmasq/dnsmasq.conf"
ln -sf /opt/router/dnsmasq/dnsmasq.conf /root/router/config/dhcp_base && echo ok || echo FAILED

echo
echo "######################################"
echo "Finished"
echo "######################################"
echo

echo "The router will be fully active the next time you boot."
echo "Make sure the original router is shutdown before booting."
echo
echo "shutting down in 5 seconds"

sleep 5
shutdown -P now
