#!/bin/sh

echo
echo "######################################"
echo "copying files"
echo "######################################"
echo

echo "copying /etc/network/interfaces.router -> /etc/network/interfaces"
cp /etc/network/interfaces.router /etc/network/interfaces

echo "copying /opt/router/dnsmasq/dnsmasq.conf.router -> /opt/router/dnsmasq/dnsmasq.conf"
cp /opt/router/dnsmasq/dnsmasq.conf.router /opt/router/dnsmasq/dnsmasq.conf

echo
echo "######################################"
echo "Remapping quickstart symlinks"
echo "######################################"
echo

echo "remapping ~/router/quickstart/network_interfaces -> /etc/network/interfaces"
ln -sf /etc/network/interfaces ~/router/quickstart/network_interfaces

echo "remapping ~/router/quickstart/dhcp_base -> /opt/router/dnsmasq/dnsmasq.conf"
ln -sf /opt/router/dnsmasq/dnsmasq.conf ~/router/quickstart/dhcp_base

echo
echo "######################################"
echo "Finished"
echo "######################################"
echo

echo "The router will be fully active the next time you boot."
echo "Make sure the original router is shutdown before booting."
echo
echo "shutting down in 5 seconds"

sleep 5
shutdown -P now
