#!/bin/sh

echo
echo "##########################################################"
echo "Checking permissions"
echo "##########################################################"
echo

echo -n "Verifying user ... "
if [ ${USER} != 'root' ]; then
	echo FAILED
	echo Not running as root, exiting.
	echo
	exit
else
	echo ok
fi

# Get version
sourceVer=$(cat /opt/router/install/.version)

echo
echo "##########################################################"
echo "Looking for modified files"
echo "##########################################################"
echo

# Get file list from archive
fileList=$(tar -tvf /opt/router/install/${sourceVer}.tar.gz | awk '{print $6}' | grep -oE '^.*/files/.*' | sed "s/.*-${sourceVer}-.*\/files\///g" | grep -vE '/$')

# Detele temp file if exists
[ -f "/tmp/$$.tmp" ] && rm /tmp/$$.tmp

for listItem in $fileList; do
	echo -n "comparing /${listItem} with /opt/router/files/${listItem} ... "

	fileLive=$(md5sum -b /${listItem}  | awk '{print $1}')
	fileOrig=$(md5sum -b /opt/router/files/${listItem} | awk '{print $1}')

	if [  "$fileLive" != "$fileOrig" ]; then
		echo yes
		echo ${listItem} >> /tmp/$$.tmp
	else
		echo no
	fi
done

echo
echo "##########################################################"
echo "creating archive of modified files"
echo "##########################################################"
echo

if [ -s "/tmp/$$.tmp" ]; then
	tar -C / -czvf /tmp/${sourceVer}-local.tar.gz -T /tmp/$$.tmp

	if [ -s "/tmp/${sourceVer}-local.tar.gz" ]; then
		mv -f /tmp/${sourceVer}-local.tar.gz /opt/router/install
		echo
		echo "Your backup of modified files can be found here :"
		echo "/opt/router/install/${sourceVer}-local.tar.gz"
	else
		echo "Backup FAILED"
	fi
else
	echo No modified files to archive ... skipping
fi

# Detele temp file if exists
[ -f "/tmp/$$.tmp" ] && rm /tmp/$$.tmp

echo
echo "##########################################################"
echo "creating archive of extra files"
echo "##########################################################"
echo

if [ -s "/opt/router/install/.extras" ]; then
	grep -vE '^( |#|$)' /opt/router/install/.extras | tar -C / -czvf /tmp/${sourceVer}-extras.tar.gz -T -

	if [ -s "/tmp/${sourceVer}-extras.tar.gz" ]; then
		mv -f /tmp/${sourceVer}-extras.tar.gz /opt/router/install
		echo
		echo "Your backup of extra files can be found here :"
		echo "/opt/router/install/${sourceVer}-extras.tar.gz"
	else
		echo "Backup FAILED"
	fi
else
	echo No extra files to archive ... skipping
fi

echo
echo "##########################################################"
echo "Done"
echo "##########################################################"
echo
