#!/bin/sh

echo
echo "######################################"
echo "Disabling ssh password access"
echo "######################################"
echo

echo -n "Enabling PubkeyAuthentication ... "
echo PubkeyAuthentication yes >> /etc/ssh/sshd_config
grep -qE '^PubkeyAuthentication yes$' /etc/ssh/sshd_config && echo ok || echo FAILED

echo -n "Disabling PasswordAuthentication ... "
echo PasswordAuthentication no >> /etc/ssh/sshd_config
grep -qE '^PasswordAuthentication no$' /etc/ssh/sshd_config && echo ok || echo FAILED

echo
echo "######################################"
echo "Finishing up"
echo "######################################"
echo

echo -n "Restarting sshd service ... "
service sshd restart
echo ok

echo
echo "######################################"
echo "Done"
echo "######################################"
echo

echo
echo Please logout and re-login using PubkeyAuthentication
echo
