#!/bin/sh

###################################################
# Read passed parameters from SYSVARS directory
###################################################
# wan-logical: Logical Interface 
# wan-physical: Physical Interface
# wan-local: Local IP
# wan-gateway: Gateway IP
###################################################

# Set SYSVARS directory
SYSVARS=/tmp/sysvars

# Read wan info
[ -f "${SYSVARS}/wan-logical" ] && LOGICAL=$(cat ${SYSVARS}/wan-logical) || exit
[ -f "${SYSVARS}/wan-physical" ] && PHYSICAL=$(cat ${SYSVARS}/wan-physical) || exit
[ -f "${SYSVARS}/wan-local" ] && LOCAL=$(cat ${SYSVARS}/wan-local) || exit
[ -f "${SYSVARS}/wan-gateway" ] && GATEWAY=$(cat ${SYSVARS}/wan-gateway) || exit

# Set tc
tc qdisc add dev $LOGICAL root handle 1: htb default 10 r2q 2500
tc class add dev $LOGICAL parent 1: classid 1:10 htb rate 1030mbit ceil 1030mbit
tc qdisc add dev $LOGICAL parent 1:10 handle 10: fq_codel ecn limit 1024

# Set static route
ip route add 10.178.0.0/16 via $GATEWAY dev ppp0 2>/dev/null

# WAN up commands
/opt/router/scripts/system/load-forwarding
/opt/router/scripts/system/irq-affinity
# /opt/router/scripts/ddns/ddns-ipv4-he-tunnel

# Load DNS redirection ipsets
cat /opt/router/nftables/dns_redirect_*.set | ipset restore

# Restart WAN dependant services
service miniupnpd restart
#service wide-dhcpv6-client restart

exit 0